const API='https://www.eustat.eus/bankupx/api/v1/es/DB';
const DATA='./data/index_es.json';
const app=document.querySelector('#app');
let catalog=[];
let state={meta:null,selections:{},result:null,table:null};

const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const fmtDate=s=>s?new Date(s).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}):'';
async function loadCatalog(){const r=await fetch(DATA);const j=await r.json();catalog=j.data||[]}
async function apiMeta(id){const r=await fetch(`${API}/${encodeURIComponent(id)}`);if(!r.ok)throw Error(`No se pudieron obtener los metadatos (${r.status})`);return r.json()}
async function apiData(id,query){const r=await fetch(`${API}/${encodeURIComponent(id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...query,response:{format:'json-stat'}})});if(!r.ok)throw Error(`La consulta ha fallado (${r.status})`);return r.json()}
function go(){render()}
function route(){const hash=location.hash||'#/';const m=hash.match(/^#\/table\/(.+)$/);if(m){openTable(decodeURIComponent(m[1]));return}renderCatalog()}
async function openTable(id){
  const table=catalog.find(x=>x.id===id); if(!table){location.hash='#/';return}
  state={meta:null,selections:{},result:null,table}; renderTableShell();
  try{state.meta=await apiMeta(id); initSelections(); renderTable();}catch(e){app.innerHTML=`<main class="catalog"><div class="catalog-inner"><div class="error">${esc(e.message)}</div></div></main>`}
}
function renderTableShell(){app.innerHTML=`<div class="shell"><aside class="rail"><button class="active"><span class="icon">☷</span>Filter</button><button><span class="icon">▥</span>Display</button><button><span class="icon">↕</span>Edit</button><button><span class="icon">⇩</span>Save</button><button><span class="icon">?</span>Help</button></aside><aside class="filter-pane" id="filters"><div class="filter-head"><h2>Filter</h2><button onclick="location.hash='#/'">Hide</button></div></aside><main class="main" id="tablemain"></main></div>`}
function initSelections(){for(const v of state.meta.variables||[]){const top=v.values?.length?Math.min(v.values.length, v.code.toLowerCase().includes('period')?5:1):0;state.selections[v.code]=top?[...v.values.slice(-top)]:[]}}
function renderTable(){
 const m=state.meta; document.querySelector('#filters').innerHTML=`<div class="filter-head"><h2>Filter</h2><button onclick="location.hash='#/'">Hide</button></div>`+(m.variables||[]).map(v=>filterCard(v)).join('');
 document.querySelector('#tablemain').innerHTML=`<div class="notice">ⓘ Consulta datos directamente desde la API pública de Eustat.</div><div class="breadcrumbs"><a href="#/">Home</a>　›　Eustat Statbank　›　${esc(m.title)}</div><section class="hero"><h1>${esc(state.table.title||m.title)}</h1><div class="meta"><span class="outline">ⓘ Information</span><span>API Eustat</span></div></section><div class="toolbar"><button onclick="runQuery()">Mostrar tabla</button><button onclick="download('csv')">CSV</button><button onclick="download('xlsx')">Excel</button><button onclick="copyQuery()">Copiar consulta API</button></div><div id="result"><div class="empty">Selecciona las variables y pulsa <strong>Mostrar tabla</strong>.</div></div>`
}
function filterCard(v){const vals=v.values||[], selected=state.selections[v.code]||[];const id='v_'+btoa(unescape(encodeURIComponent(v.code))).replace(/=/g,'');return `<section class="card"><h3>${esc(v.text)}</h3><span class="pill">${selected.length} de ${vals.length} seleccionados</span><div class="selection"><div class="select-actions"><button onclick="selectAll('${esc(v.code)}')">Todos</button><button onclick="clearAll('${esc(v.code)}')">Ninguno</button></div><div class="value-list">${vals.map((x,i)=>`<label class="value-row"><input type="checkbox" ${selected.includes(x)?'checked':''} onchange="toggleValue(${JSON.stringify(v.code)},${JSON.stringify(x)},this.checked)"><span>${esc(v.valueTexts?.[i]??x)}</span></label>`).join('')}</div></div></section>`}
function toggleValue(code,val,on){state.selections[code]=state.selections[code]||[];if(on&&!state.selections[code].includes(val))state.selections[code].push(val);if(!on)state.selections[code]=state.selections[code].filter(x=>x!==val);renderFiltersOnly()}
function renderFiltersOnly(){document.querySelector('#filters').innerHTML=`<div class="filter-head"><h2>Filter</h2><button onclick="location.hash='#/'">Hide</button></div>`+(state.meta.variables||[]).map(filterCard).join('')}
function selectAll(code){const v=state.meta.variables.find(x=>x.code===code);state.selections[code]=[...(v.values||[])];renderFiltersOnly()}
function clearAll(code){state.selections[code]=[];renderFiltersOnly()}
function buildQuery(){return {query:(state.meta.variables||[]).filter(v=>state.selections[v.code]?.length).map(v=>({code:v.code,selection:{filter:'item',values:state.selections[v.code]}}))}}
async function runQuery(){const result=document.querySelector('#result');result.innerHTML='<div class="loading">Consultando Eustat…</div>';try{state.result=await apiData(state.table.id,buildQuery());result.innerHTML=renderJsonStat(state.result)}catch(e){result.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function renderJsonStat(j){if(!j||!j.id||!j.dimension)return '<div class="empty">La API no devolvió un conjunto de datos reconocible.</div>';const ids=j.id, sizes=j.size;const rows=[];function coords(n,prefix=[]){if(n===ids.length){rows.push(prefix);return}for(let i=0;i<sizes[n];i++)coords(n+1,[...prefix,i])}coords(0);const labels=ids.map(id=>{const d=j.dimension[id];const idx=d.category?.index||{};const keys=Array.isArray(idx)?idx:Object.keys(idx).sort((a,b)=>idx[a]-idx[b]);return {id,label:d.label||id,keys,text:keys.map(k=>d.category.label?.[k]??k)}});let html='<div class="table-wrap"><table class="result-table"><thead><tr>'+labels.map(x=>`<th>${esc(x.label)}</th>`).join('')+'<th>Valor</th></tr></thead><tbody>';rows.slice(0,2000).forEach((coord,n)=>{const flat=coord.reduce((a,x,i)=>a*sizes[i]+x,0);html+='<tr>'+coord.map((x,i)=>`<td>${esc(labels[i].text[x])}</td>`).join('')+`<td>${esc(j.value?.[flat]??'')}</td></tr>`});html+='</tbody></table></div>';if(rows.length>2000)html+=`<p class="status">Mostrando 2.000 de ${rows.length.toLocaleString('es-ES')} celdas.</p>`;return html}
async function download(format){if(!state.table)return;try{const r=await fetch(`${API}/${encodeURIComponent(state.table.id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...buildQuery(),response:{format}})});if(!r.ok)throw Error(`Descarga fallida (${r.status})`);const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.table.id}.${format==='xlsx'?'xlsx':'csv'}`;a.click();URL.revokeObjectURL(a.href)}catch(e){alert(e.message)}}
async function copyQuery(){const q=JSON.stringify(buildQuery(),null,2);await navigator.clipboard.writeText(`${API}/${state.table.id}\n\nPOST body:\n${q}`);alert('Consulta API copiada.')}
function renderCatalog(){app.innerHTML=`<main class="catalog"><div class="catalog-inner"><h1>Eustat Statbank</h1><p>Explora las tablas estadísticas de Eustat con una experiencia inspirada en PxWeb 2. El catálogo se genera desde el índice local y los datos se consultan directamente en la API de Eustat.</p><div class="search"><input id="q" placeholder="Buscar por título, operación, variable o palabra clave…" autocomplete="off"></div><div class="catalog-grid"><aside class="filters"><div class="filter-block">Contenido</div><div class="filter-block">Operación estadística</div><div class="filter-block">Frecuencia</div><div class="filter-block">Periodo</div></aside><section><div class="results-head"><strong id="count">${catalog.length.toLocaleString('es-ES')} tablas</strong><span>Ordenadas por actualización</span></div><div id="cards"></div></section></div></div></main>`;const q=document.querySelector('#q');q.addEventListener('input',()=>paintCards(q.value));paintCards('')}
function paintCards(term){const t=term.trim().toLocaleLowerCase('es');const rows=catalog.filter(x=>!t||(x.search_text||x.title||'').toLocaleLowerCase('es').includes(t)).sort((a,b)=>String(b.updated).localeCompare(String(a.updated)));document.querySelector('#count').textContent=`${rows.length.toLocaleString('es-ES')} tablas`;document.querySelector('#cards').innerHTML=rows.slice(0,100).map(x=>`<article class="table-card"><h2>${esc(x.title||x.text)}</h2><p><strong>${esc(x.id)}</strong> · ${esc(x.first_period||'')} ${x.last_period?'— '+esc(x.last_period):''} · Actualizada ${esc(fmtDate(x.updated))}</p><div class="tags">${x.operacion_titulo?`<span class="tag">${esc(x.operacion_titulo)}</span>`:''}${x.frecuencia?`<span class="tag">${esc(x.frecuencia)}</span>`:''}${(x.variables||[]).slice(0,5).map(v=>`<span class="tag">${esc(v.text||v)}</span>`).join('')}</div><a class="open" href="#/table/${encodeURIComponent(x.id)}">Abrir tabla →</a></article>`).join('')||'<div class="empty">No se encontraron tablas.</div>'}
loadCatalog().then(()=>route()).catch(e=>app.innerHTML=`<main class="catalog"><div class="catalog-inner"><div class="error">No se pudo cargar el catálogo: ${esc(e.message)}</div></div></main>`);
window.addEventListener('hashchange',route);window.runQuery=runQuery;window.toggleValue=toggleValue;window.selectAll=selectAll;window.clearAll=clearAll;window.download=download;window.copyQuery=copyQuery;
